import { stat, writeFile } from 'node:fs/promises';

const pages = [
  { loc: 'https://stegzero.com/', file: new URL('../index.html', import.meta.url) },
  { loc: 'https://stegzero.com/invisible-character-detector/', file: new URL('../invisible-character-detector/index.html', import.meta.url) }
];

const entries = await Promise.all(pages.map(async page => {
  const info = await stat(page.file);
  return `  <url>\n    <loc>${page.loc}</loc>\n    <lastmod>${info.mtime.toISOString().slice(0, 10)}</lastmod>\n  </url>`;
}));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/update-sitemap.mjs. Do not edit manually. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>
`;

await writeFile(new URL('../sitemap.xml', import.meta.url), xml);
