import { execFileSync } from 'node:child_process';
import { readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const baseUrl = (process.env.SITE_URL || 'https://stegzero.com').replace(/\/$/, '');
const excludedDirectories = new Set(['.git', '.github', 'node_modules']);
const excludedPages = new Set(['404.html']);
const homepageDependencies = [
  'android-chrome-192x192.png',
  'android-chrome-512x512.png',
  'apple-touch-icon.png',
  'brand-mark.png',
  'favicon-16x16.png',
  'favicon-32x32.png',
  'favicon.ico',
  'icon.svg',
  'logo.svg',
  'preview-image.png',
  'site.webmanifest'
];

async function findHtmlFiles(directory = root) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    if (entry.name.startsWith('.') && entry.isDirectory()) continue;

    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (!excludedDirectories.has(entry.name)) {
        files.push(...await findHtmlFiles(absolutePath));
      }
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      const relativePath = path.relative(root, absolutePath);
      if (!excludedPages.has(relativePath)) files.push(relativePath);
    }
  }

  return files;
}

function gitSucceeds(args) {
  try {
    execFileSync('git', args, { cwd: root, stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function isTracked(relativePath) {
  return gitSucceeds(['ls-files', '--error-unmatch', '--', relativePath]);
}

function isDirty(relativePath) {
  if (!isTracked(relativePath)) return true;
  return !gitSucceeds(['diff', '--quiet', '--', relativePath])
    || !gitSucceeds(['diff', '--cached', '--quiet', '--', relativePath]);
}

async function existingSources(relativePath) {
  const candidates = relativePath === 'index.html'
    ? [relativePath, ...homepageDependencies]
    : [relativePath];
  const sources = [];

  for (const candidate of candidates) {
    try {
      await stat(path.join(root, candidate));
      sources.push(candidate);
    } catch {
      // Optional homepage assets should not stop sitemap generation.
    }
  }

  return sources;
}

async function lastModified(relativePath) {
  const sources = await existingSources(relativePath);
  const dirtySources = sources.filter(isDirty);

  if (dirtySources.length > 0) {
    const modifiedTimes = await Promise.all(
      dirtySources.map(async source => (await stat(path.join(root, source))).mtimeMs)
    );
    return new Date(Math.max(...modifiedTimes)).toISOString().slice(0, 10);
  }

  try {
    const timestamp = execFileSync(
      'git',
      ['log', '-1', '--format=%cI', '--', ...sources],
      { cwd: root, encoding: 'utf8' }
    ).trim();
    if (timestamp) return timestamp.slice(0, 10);
  } catch {
    // Fall back to the file timestamp outside a Git checkout.
  }

  return (await stat(path.join(root, relativePath))).mtime.toISOString().slice(0, 10);
}

function pageUrl(relativePath) {
  const normalized = relativePath.split(path.sep).map(encodeURIComponent).join('/');
  if (normalized === 'index.html') return `${baseUrl}/`;
  if (normalized.endsWith('/index.html')) {
    return `${baseUrl}/${normalized.slice(0, -'index.html'.length)}`;
  }
  return `${baseUrl}/${normalized}`;
}

function escapeXml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

const pages = (await findHtmlFiles()).sort((a, b) => {
  if (a === 'index.html') return -1;
  if (b === 'index.html') return 1;
  return a.localeCompare(b);
});

const urls = await Promise.all(pages.map(async page => ({
  loc: pageUrl(page),
  lastmod: await lastModified(page)
})));

const urlEntries = urls.map(({ loc, lastmod }) => [
  '  <url>',
  `    <loc>${escapeXml(loc)}</loc>`,
  `    <lastmod>${lastmod}</lastmod>`,
  '  </url>'
].join('\n')).join('\n');

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/update-sitemap.mjs. Do not edit manually. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  urlEntries,
  '</urlset>',
  ''
].join('\n');

await writeFile(path.join(root, 'sitemap.xml'), sitemap, 'utf8');
console.log(`Updated sitemap.xml with ${urls.length} URL${urls.length === 1 ? '' : 's'}.`);
